click("element1.png")
wait(2)
click("element2.png")
wait(2)
type("First Note")
wait(2)
click("element3.png")
wait(2)
type("this is the first note")
wait(2)
click("element4.png")
wait(2)
exists("element5.png")
