click("element1.png")
wait(2)
click("element2.png")
wait(2)
click("element3.png")
wait(2)
type("Discard This Checklist")
wait(2)
click("element4.png")
wait(2)
click("element5.png")
wait(2)
exists("element6.png")
